### ISSUE TITLE
Passive options for intransitive verbs

### ISSUE THREAD

**Issue by dan-simon** [cashmonides/sentence_graph#2]
As this issue says, we currently have passive options for intransitive verbs, since our rules do not apply to option determination. Furthermore, given only the functions we have, there is no way (even a hacky way) to filter out such options. Here are the possibilities:
- We could change our prune_tf_space function, which gets translation formulae with voice determined, and let it use the lexeme. This seems to be exactly the opposite of modularity, though.
- We could change what arguments we feed in (specifically the "allowed" argument) based on the lexeme. This, however, still seems hacky.
- We could do additional processing on our output, either by adding a new active-passive dictionary or doing something smart (since translation formulae have no voice). This seems just as hacky as the second option, though.

Note: I plan to add a comment with a solution which I plan to implement, along the lines of the second option.

**Comment by cashmonides** [comment]
Hi Dan
That's a good point! Second option seems wise to me. Option determination
should be based on the lexeme after all.

Akiva

**Comment by dan-simon** [comment]
Solution: We follow the second option. However, rather than being naive, we have a dictionary looking like this:
`{core: {transitivity: {intransitive: {voice: ['active']}}}}`
which matches with the lexeme and imposes things. In this case, `{intransitive: {voice: ['active']}}` matches with the transitivity, so if the transitivity is in `{intransitive: {voice: ['active']}}`, the corresponding constraint, here `{voice: ['active']}`, will be activated, which will remove voices other than 'active'.

Also, let's take this conversation to a notes file; I was doing this to test issues as much as anything else.
